### ISSUE TITLE
Create Jenkinsfile

### ISSUE THREAD

**Issue by rajeshgheware** [brainupgrade-in/copilot-weather#22]
Jenkins should trigger the build whenever any tag is created.
Jenkins should create docker image brainupgrade/copilot-weather and give use github tag as the image tag too
Deploy the docker image to integration env (Kubernetes cluster)
Wait for the user input,  once approval is received then deploy the same image in UAT Kubernetes cluster
Wait for the user input,  once approval is received then deploy the same image in PROD Kubernetes cluster

**Comment by brainupgrade-in** [comment]
Create placeholder for kubernetes deployments
